// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnEbmbnX4tlTGGmetli36zGot2qWcWvVM',
    appId: '1:586143236644:web:2942f2386dbd5e70ad0eb1',
    messagingSenderId: '586143236644',
    projectId: 'pickuplines-82369',
    authDomain: 'pickuplines-82369.firebaseapp.com',
    storageBucket: 'pickuplines-82369.appspot.com',
    measurementId: 'G-QYB4GVD9KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzskA7Qev-kY6b_HIi9hL23M4bBqeKnT8',
    appId: '1:586143236644:android:f738b7a986e953e8ad0eb1',
    messagingSenderId: '586143236644',
    projectId: 'pickuplines-82369',
    storageBucket: 'pickuplines-82369.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnEbmbnX4tlTGGmetli36zGot2qWcWvVM',
    appId: '1:586143236644:web:e7e04208315fcaeaad0eb1',
    messagingSenderId: '586143236644',
    projectId: 'pickuplines-82369',
    authDomain: 'pickuplines-82369.firebaseapp.com',
    storageBucket: 'pickuplines-82369.appspot.com',
    measurementId: 'G-3X3LN8MPWM',
  );

}